CREATE TABLE `Student`(
    `student_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `nameStudent` VARCHAR(255) NOT NULL,
    `phoneStudent` INT NOT NULL,
    `emailStudent` VARCHAR(255) NOT NULL,
    `numberOfCurses` INT NOT NULL
);
CREATE TABLE `Follow Up`(
    `teacher_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `registerOfEstudent` VARCHAR(255) NOT NULL
);
CREATE TABLE `Registro`(
    `InfoStudiant` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `Registro` ADD PRIMARY KEY(`InfoStudiant`);
CREATE TABLE `Faculty`(
    `faculty_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `department` VARCHAR(255) NOT NULL,
    `city` VARCHAR(255) NOT NULL
);
CREATE TABLE `Exam`(
    `Exam_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `subjects` VARCHAR(255) NOT NULL,
    `notes` DOUBLE(8, 2) NOT NULL
);
CREATE TABLE `Course`(
    `course_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `student_id` BIGINT NOT NULL,
    `teacher_id` BIGINT NOT NULL,
    `nameCourse` VARCHAR(255) NOT NULL,
    `credits` INT NULL
);
CREATE TABLE `Parent Information`(
    `infoParents_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `studentRelation` VARCHAR(255) NOT NULL,
    `nameParent` VARCHAR(255) NOT NULL,
    `phoneParent` INT NOT NULL
);
CREATE TABLE `Number Of Courses`(
    `courses_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE `Teacher`(
    `course_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE `Assists`(
    `student_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `assists` VARCHAR(255) NOT NULL
);
CREATE TABLE `Departament`(
    `department_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `courses` VARCHAR(255) NOT NULL,
    `teachers` VARCHAR(255) NOT NULL
);